import "@/styles/globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { cn } from "@/lib/cn";
import Navbar from "@/components/Navbar";
import GoUpButton from "@/components/GoUpButton";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={cn("min-h-screen text-xl", inter.className)}>
        <Navbar />
        {children}
        <GoUpButton />
      </body>
    </html>
  );
}
